### ISSUE TITLE
Scala 3

### ISSUE THREAD

**Issue by lutzh** [scala-hamburg/scala-hamburg#14] opened 2018-06-01 14:49 UTC
What's new in Scala 3? Comprehensive overview, goal would be to cover most of http://dotty.epfl.ch/docs/reference/overview.html and give motivation examples.

**Comment by markusjura** [comment] 2021-04-28 16:08
Duplicate of:
- https://github.com/scala-berlin/scala-berlin/issues/10
- https://github.com/scala-berlin/scala-berlin/issues/13

**Closed as completed by markusjura** 2021-04-28 16:08 UTC
Labels: idea
